### ISSUE TITLE
missing DynamoInventor.dll?

### ISSUE THREAD

**Issue by jluebker** [frankfralick/DynamoInventor#4]
It's pretty clear where the Autodesk.dynamoInventor.Inventor.addin needs to go, but its pointing at a DynamoInventor.dll that does not seem to exist in the downloaded contents... am I missing something?

**Comment by AlexFielder** [comment]
Isn't the DynamoInventor.dll supposed to be the result of whatever you compile this solution to? I.e. {MySolutionName}.dll

**Comment by jluebker** [comment]
Thanks, I figured that out after I'd posted this. Still having trouble compiling though. Working with Frank on this.

Jeremy Luebker
Arch II
t 415.546.2957
c 510.881.3682
Perkins+Will

**Comment by AlexFielder** [comment]
FWIW: I was able to get this to compile. And the ribbon loads inside of Inventor, but when I click the button nothing happens and the addin errors with a "file not found" error- I assume this is because the Inventor libraries created as part of the solution are being copied to the wrong location.

**Comment by jluebker** [comment]
That's great! Nice job.

Just to check does the addin file show as loaded in the inventor addins menu?

If I can replicate the state you gotten to we could possibly scrub through the code to see where it is expecting the libraries to be and manually put them there.

I hope you don't mind if I pick your brain a bit here as you have gotten farther than I did:

I assume you are running inventor 2015.

Are you using the most recent build of dynamo or did you have to compile the dynamo build from Github?

What changes did you have to make? Was it just the location of the dynamo core.dll that we had discussed last?

I think it would behoove us, if we can get this working, to document it and add the document as an installation how-to to the Github until someone can get it working properly...

Jeremy Luebker
Arch II
t 415.546.2957
c 510.881.3682
Perkins+Will

**Comment by AlexFielder** [comment]
Hi Jeremy,

I am running Inventor 2016 but the addin loads inside of Inventor 2015 too.

I have the latest copy of Dynamo installed which is why I think the location of the Inventor library files is important.

And I absolutely agree that if we can get it working we should add it to this solution.

I actually forked this solution to see if I could get it working- I'm not sure how that works having never contributed to a solution here before.

**Comment by jluebker** [comment]
Hi Alex,

Ah ok. I think I know what is happening. Frank built this version on Inventor 2015. In my correspondence with him, he mentioned that the code will need to be updated to work with 2016. There are several places in the code where he has noted parts of the code that will need to be updated in order for it to work with 2016. I think it would be best if we can get this working for 2015 and then tackle 2016.

You said it already loads into your 2015, are you getting the same error about the files missing in 2015?

When you say you forked it… did you download the zip or did you us github desktop? (yes I’m a github noob)

Jeremy Luebker
Arch II
t 415.546.2957
c 510.881.3682
Perkins+Will

**Comment by jluebker** [comment]
Hi Alex,

I’m giving this another shot:

Did you run into a similar error? If so how did you fix it?
Is this how you changed the location to read the latest version of dynamo?
See image...

![dynamoinventorerror1](https://cloud.githubusercontent.com/assets/4041748/12192186/5e7de858-b591-11e5-99d2-b7c4065b554f.PNG)

**Comment by AlexFielder** [comment]
The bigger question is what "using blah.blah;" did you have to include to get the DynamoPathManager to work correctly in that image?

**Comment by jluebker** [comment]
if you do a simple search in the entire project... you get tons of hits on InventorLibrary.whateverwhatever.... I get the sens this is a pretty important part of the project... question is where is its location declared so we can point it to the correct place, why is it not in the correct place and where can we find it...?

**Comment by jluebker** [comment]
![image](https://cloud.githubusercontent.com/assets/4041748/12205947/080418b4-b5f3-11e5-812e-18e7790ac886.png)
look at the InventorLibrary project and got this... possibly why it doesn't build properly?

**Comment by jluebker** [comment]
![image](https://cloud.githubusercontent.com/assets/4041748/12207537/08e3e65c-b5fc-11e5-8fe8-3d4c5af3a1c9.png)
in trying to build InventorLibrary... i got this error:
it looks like this part of the project is trying to find the InventorLibrary.dll in the dynamo github repository...uggg...

**Comment by AlexFielder** [comment]
Hi Jeremy,

Unless I am mistaken, the InventorLibrary project simply needs a reference
to the inventorservices.dll file - whether or not these two .dll files
ultimately need to be in a folder that Dynamo can see/load from remains an
issue and one that will only be solved by close scrutiny of the Dynamo
source itself.

The key thing here is to remember that the InventorLibrary relies upon the
InventorServices project getting built first. DynamoInventor project relies
on both being built.

I read this article before Christmas about a process called "Zero Touch
Import" which means Dynamo can simply load a series of .dll libraries and
be able to interact with the program the libraries were built for:
http://dynamoprimer.com/10_Packages/10-5_Zero-Touch.html

This is what I think the Inventor Addin is attempting to do by including
both the InventorLibrary and InventorServices projects, but without the
manual steps that the above article mentions and whilst also presenting an
environment that Dynamo can interact with inside of Inventor.

Thanks,

Alex.

**Comment by jluebker** [comment]
![image](https://cloud.githubusercontent.com/assets/4041748/12210052/2fbd6ad6-b60c-11e5-80c9-2c87ad563351.png)

the InventorServices project is missing only one reverence:  DSNodeServices.dll if you look at other dynamo packages such as dynamo unfold... they are relying on this. Is this possibly an old reference no longer included in dynamo builds?

**Comment by jluebker** [comment]
as to the location ... if you open the CS.config file in the Config folder, there are references to "Dynamo 7.0" not sure but this might be something to look into

**Comment by jluebker** [comment]
just for the heck of it, i installed dynamo 7.5 sure enough a lot of the dll references that are missing in the references section show up in this earlier build of dynamo main directory. however, simply redirecting the reference of the dynamo directory is not enough to resolve the broken references

**Comment by AlexFielder** [comment]
Yes it is. Change this reference to dynamoservices.dll in the dynamo
install folder

**Comment by jluebker** [comment]
ooooh you are right... that actually resolves most of the reference issues. got the InventorServices.dll to compile. Running into some .net framework errors when trying to compile the InventorLibrary.dll .... i'm guessing this is due to the fact that dynamo 9.0 has switched to using .net framework 4.5... maybe resolving the references with an older version would be better?

![image](https://cloud.githubusercontent.com/assets/4041748/12212829/92936b30-b623-11e5-81df-3de470bbb2e0.png)

**Comment by jluebker** [comment]
nm... that was actually really easy to fix... just change the project properties

**Comment by jluebker** [comment]
ok this is good... i got the InventorSerivices and InventorLibrary to compile... i'm getting a couple of errors when building the DynamoInventor... can you make anything of these?

![image](https://cloud.githubusercontent.com/assets/4041748/12213336/330cf2c8-b62b-11e5-99ca-74c4a07f4af1.png)

**Comment by jluebker** [comment]
also Alex, maybe this helps, maybe it doesn't, with regards to your question about where does all of this go once its compiles... frank has another repository for a simple inventor addin. the readme file is quite telling and maybe gives us a hint...

https://github.com/frankfralick/InventorAddIns/tree/master/SimpleAddIn

though looking at the way dynamo for revit was built, the Revit_20xx folder with everything in it is in the dynamo directory of the current dynamo version you are using...

**Comment by AlexFielder** [comment]
I'm aware of where the add-in needs to go in order for inventor to load it;
Normally it will be something like:

%appdata%\autodesk\applicationplugins{project name}\

My earlier point was regarding whether the inventorlibrary and inventor
services projects also need to be in that location.

Thinking about it as I typed the above sentence, it makes it easier if they
do all end up in the same folder; it may be a requirement of dynamo however
that they are in a sub folder within dynamo's files.

:-)

**Comment by jluebker** [comment]
I was being captain obvious so this can get documented. I agree with you, if we think ahead, if this is ever to become as official an a release as dynamo for rivet, we should probably follow suite and put it in the dynamo folder. this will allow multiple versions of dynamo to be loaded as with revit as well as multiple versions of inventor to be handled with each version of dynamo.

Peaking a head a bit... looks like once we get the above issue sorted out and the addin to load correctly, we might need to start working on the node library
![image](https://cloud.githubusercontent.com/assets/4041748/12217149/d13661ba-b6ac-11e5-8aa2-155b5dc1d9f6.png) (these are the components that frank showed in his youtube post here: https://www.youtube.com/watch?v=rRjLnWOCBIs, so we know the Inventor library works in Dynamo)

I still couldn't get my last dll to compile so i downloaded your fork to see. It compiled with the exception of the following error:

Error   6   The command "call "%VS110COMNTOOLS%vsvars32"
            mt.exe -manifest "C:\Users\LuebkerJ\Downloads\DynamoInventor-master\DynamoInventor-master\src\DynamoInventor\DynamoInventor.X.manifest" -outputresource:"C:\Users\LuebkerJ\Downloads\DynamoInventor-master\DynamoInventor-master\src\DynamoInventor\bin\Debug\DynamoInventor.dll";#2
XCopy "C:\Users\LuebkerJ\Downloads\DynamoInventor-master\DynamoInventor-master\src\DynamoInventor\bin\Debug*" "%AppData%\Autodesk\ApplicationPlugins\DynamoInventor\" /Y /R /I /S

XCopy "C:\Users\LuebkerJ\Downloads\DynamoInventor-master\DynamoInventor-master\src\DynamoInventor\Autodesk.DynamoInventor.Inventor.addin" "%AppData%\Autodesk\ApplicationPlugins\DynamoInventor\" /Y /R" exited with code 1.    DynamoInventor

![image](https://cloud.githubusercontent.com/assets/4041748/12217264/63efca3e-b6b0-11e5-9f71-2d1bbd64c153.png)

**Comment by jluebker** [comment]
something interesting:

for the addin to even "see" the dynamoinventor.dll it needs to be bin in the C:\Program Files\Autodesk\Inventor 2015\Bin folder.

![image](https://cloud.githubusercontent.com/assets/4041748/12217427/c261ff84-b6b4-11e5-9b17-e8d13e43dda2.png)

Once before (back when I had started looking into this) some how i had managed to get the addin to load, and the icon to show up in inventor, but nothing would happen when i clicked on it (for all the reasons we have been working through). I'll keep trying to wrack my brain and see if i can remember what I did...

**Comment by jluebker** [comment]
ok interesting... if you put all 3 dlls into the bin folder mentioned above, the addin button shows up (minus the logo, though nothing happens when you click on it).

![image](https://cloud.githubusercontent.com/assets/4041748/12218576/38bd415c-b6d8-11e5-8eec-b3b38d0e541f.png)

i'm starting to think this is what frank was talking about here:
![image](https://cloud.githubusercontent.com/assets/4041748/12218626/86386f50-b6d9-11e5-8f16-5ce1d87c0cb3.png)

**Comment by AlexFielder** [comment]
Hi Jeremy,

Inventor being able to load the add-in (or otherwise) hinges on the
information contained within the .addin file that gets copied during the
post-build event.

I too had the add-in loading but the button not working.

I think it has to do with the overly complicated way in which the button is
created/defined.

A recent add-in I wrote had a button defined and added to the ribbon in
less than 20 lines.

I'm not really sure why in this solution it is so complicated; perhaps
Frank can answer that question? I think it's just a throw back to the pre
registry-free add-in days as I have seen a similar approach in a solution
from 2013.

**Comment by jluebker** [comment]
see comment on https://github.com/frankfralick/DynamoInventor/issues/1
